### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by blakie21737** [RecaMedia/Backdoor-Release#1]
Hi I'm having an issue where I have copied the files in a directory called /bkdr/ at the root of my server directory, I do get a splash screen more specifically "a black background displaying the assets/IMG/loading_blocks.svg file" but it doesn't go any further than that. I have tried this page on lighttpd, nginx and Apache server on both mobile and PC in both Chrome, Firefox and Microsoft edge I'm running PHP V7.2.3 I have also tried PHP V7.2.0 in all configurations and alternitives. what am I doing wrong?

**Comment by RecaMedia** [comment]
Hi there. You simply need to copy/move the bkdr folder to your root, not move the files out of the bkdr folder. But technically I don’t think this would be the issue. Do you have a URL that you can share? Or does your browser’s console log show any errors?

**Comment by blakie21737** [comment]
Hey thanks for your reply, and sorry for the late reply my partner had a baby yesterday morning. yeah it is installed as such, The URL is 101.0.75.64 and obviously under the bkdr directory, now that I check I am getting repeated console errors but can't understand why. Thanks so much for your assistance and I am excited in getting this solved.

**Comment by RecaMedia** [comment]
Hey Blakie, I just took a look at the URL. It seems you need to install the sqlite3 module for PHP on your server. If you goto http://101.0.75.64/bkdr/ and look at your developer tools > Network > XHR, you'll see a call to config/ which isn't returning a json object due to a fatal error with PHP. I think once you resolve this, it should hopefully work. Best!

**Comment by blakie21737** [comment]
Thanks for your continued support! Interesting conundrum, I see now that it is a mere server issue; of what the issue is I'm unsure. I installed wamp and it works perfectly on that platform, since then I have bought a VPS and installed apache2, PHP7.0, MariaDB. I installed sqlite3 and it still isn't working unfortunately, I then installed all of the various PHP modules that wamp came packaged with and there was still no luck. The address is http://139.99.195.212/ I have made a PHP info file so you can inspect the PHP environment and bkdr is installed with a fresh download.

**Comment by blakie21737** [comment]
Also if you would like the SSH credentials let me know and I can send them via private message.

**Comment by RecaMedia** [comment]
Sure no problem. After reviewing the URL, it looks like you're having a similar issue. You're not able to retrieve the config json from the config ajax call not due to an error this time, but because .htaccess being denied to redirect. The way the /api works, it redirects all traffic within /api to the index.php file. You have to allow .htaccess files to work within the /bkdr directory and subdirectories.

**Comment by blakie21737** [comment]
Hello again, I fell like I've been an annoying fly constantly buzzing around and annoying you this week! =P Well we are so close now its not funny! I resolved the .htaccess issue and the call to config resolves in a status code 200 OK. but still fails to load. =( I believe its caused by an error in the console that stipulates:

SyntaxError: Unexpected token < in JSON at position 0

I looked at the bkdr.js file in formatted mode to make it readable, and navigated to the error on line 14852 but i couldn't make any sense of it, unfortunately I'm not a developer. =P

*************
Issue Solved!!! =D

I thought i would leave my original message i was typing for you because i don't know why, it might help someone else as noobish as me! =P

I looked at the call to config again and looked at the response tab and it was trying to use mcrypt which i didn't have installed. Once installed i refreshed and it opened to the installation page without a hitch. =D

Thanks so much for the help!

**Comment by RecaMedia** [comment]
Awesome! I'm glad you have it working. No worries on the reporting the issues, I truly appreciate the fact my software is being used. Also, having this issue reported would help others as you've mentioned. If you're ever interested looking under the hood, visit https://github.com/recamedia/Backdoor. I'll update the readme file for this repo to make sure users have the proper modules installed. I'll close this issue. Best!
