### ISSUE TITLE
Infinite loading screen

### ISSUE THREAD

**Issue by Macemas** [RecaMedia/Backdoor-Release#3]
I've tried installing backdoor v2 on my cpanel server and I haven't managed to get the installer to initiate. After extracting the file, and opening the url it is just a loading image (squares)

**Comment by RecaMedia** [comment]
Hi @Macemas, have you looked at the developers console within your browser? any errors? You most likely have an error of some sort. Check your network calls and see what responses you have.

Just as a side note, make sure you have **Sqlite3**, and **Mcrypt** module installed within your _**PHP.ini**_ file. Also, check that **.htaccess** files are functioning as well.

**Comment by RecaMedia** [comment]
@Macemas I haven't heard back so I'm going to assume you have this working and close this ticket.

**Comment by orbli** [comment]
While I love the idea of the project, I have an exactly same problem using it.

I run my own copy at `/bkdr` and find the following:

![image](https://user-images.githubusercontent.com/6440599/45810549-6f9b5a00-bcfd-11e8-8bf1-30b232bf13f3.png)

It seems I need to work on my config (but where is it?) to change my address;
I also need to activate something else on port 3001 which I'm not sure what it is;
and also i wonder why there is a fail `/bkdr/api/config/:1` call on first line?

on LAMP, i use ubuntu18.04, apache2, php7.2, mysql, also php-sqlite3, also mod_rewrite. anything I miss?

**Comment by orbli** [comment]
Activated Sqlite3 and Mcrypt

![image](https://user-images.githubusercontent.com/6440599/45811133-e422c880-bcfe-11e8-84ed-eb0f48b51b06.png)
![image](https://user-images.githubusercontent.com/6440599/45811154-f00e8a80-bcfe-11e8-93ac-4f885b59caa7.png)

**Comment by RecaMedia** [comment]
Hi @orbli,
When you visit `youraddress/bkdr`, it's supposed to load an install file `/api/install.php`, which creates the config.json in your root directory of `/bkdr`. From there, `/api/index` needs to read your config file, which gets read via the front-end code. There most be some error along the way. Have you looked into your PHP logs?

**Comment by orbli** [comment]
I catch these lines from `/var/log/apache2/*` when I access the server, seems nothing informative

```
[server_ip] - - [21/Sep/2018:00:31:44 +0900] "GET /bkdr/ HTTP/1.1" 200 623 "http://[server_ip]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
[server_ip] - - [21/Sep/2018:00:31:44 +0900] "POST /bkdr/api/config/ HTTP/1.1" 404 507 "http://[server_ip]/bkdr/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
```

**Comment by orbli** [comment]
I try to put it at root but no luck
```
[server_ip] - - [21/Sep/2018:00:53:02 +0900] "GET / HTTP/1.1" 200 624 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
[server_ip] - - [21/Sep/2018:00:53:02 +0900] "GET /assets/css/main.css HTTP/1.1" 200 24528 "http://[server_ip]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
[server_ip] - - [21/Sep/2018:00:53:02 +0900] "GET /assets/js/bkdr.js HTTP/1.1" 200 372335 "http://[server_ip]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
[server_ip] - - [21/Sep/2018:00:53:03 +0900] "POST /api/config/ HTTP/1.1" 404 502 "http://[server_ip]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
[server_ip] - - [21/Sep/2018:00:53:03 +0900] "GET /assets/img/loading_blocks.svg HTTP/1.1" 200 1274 "http://[server_ip]/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
```
However, when I access `/api/install.php` directly, I can see something interesting:
```
{"success":false,"statusMessage":"There was an error creating configuration file. Super user has been created. Setting for Open Registration has been applied. Setting for Sending Errors has been applied.\n\nInstallation process has been completed with errors.\n\nYour default login credentials are USER: (The email provided), PASS: admin."}
```
I guess it might be `.htaccess` problem, but I have no enough knowledge to verify this part

**Comment by RecaMedia** [comment]
@orbli Possibly a permission issue? Where www-data user doesn't have permission to create a file? Try manually creating the `config.json` file using the following sample:

```
{
    "backdoorDir": "bkdr",
    "backdoorDomain": "http:\/\/localhost",
    "changeRoot": "_demo-root",
    "defaultTheme": "monokai",
    "domainIsBackdoorApp": "true",
    "fontSize": "12px",
    "lineWrapping": true,
    "multiViewColors": [
        "#007fff",
        "#04ff00",
        "#ff8300"
    ],
    "tabSize": 2
}
```

Maybe this can at least get it functioning.

**Comment by orbli** [comment]
I have now figured out the default setting
```
<Directory /var/www/>
	Options Indexes FollowSymLinks
	AllowOverride None
	Require all granted
</Directory>
```
inhibit the use of .htaccess. Now using `AllowOverride All` solves the problem of 404 on /api/config/

However, I still face problem on invalid syntax of bkdr.js:12
![image](https://user-images.githubusercontent.com/6440599/45832324-2b777c00-bd34-11e8-8e63-5581de5c523c.png)

and your manual config did not solve it either. 

I noticed that when actually calling `/api/install.php` without .htaccess masking, it needs write access, so maybe this worths dropping down in installation note too

**Comment by orbli** [comment]
I have removed `console.error(e)` on line 12 that chrome tells me where it occurs, successfully remove that syntax error, and yet the web still polling at `localhost:3001` which I have still no idea what to do with it

**Comment by RecaMedia** [comment]
So are you now able to use the application?

I'll make sure to add the writes permission to the notes.

> I have removed `console.error(e)` on line 12 that chrome tells me where it occurs, successfully remove that syntax error, and yet the web still polling at `localhost:3001` which I have still no idea what to do with it

You don't have to worry about the call being made to port 3001, that is a feature for collaborative coding that is still incomplete and it shouldn't effect the application.

**Comment by orbli** [comment]
still cannot use, stuck at loading screen

I used your template configuration, no luck

**Comment by RecaMedia** [comment]
Have you looked at your network tab within the developer console to see what response you're getting from the failed call?

**Comment by orbli** [comment]
Nothing actually failed if we ignore the `localhost:3001` call

![image](https://user-images.githubusercontent.com/6440599/45835844-c2950180-bd3d-11e8-8e4f-da86a4ee8436.png)

**Comment by RecaMedia** [comment]
Hmm, this is interesting. Do you have a URL where I can take a look? I'm not sure why no calls are not being made. There is a sequence of calls that should be made in the following order, see below:

![capture](https://user-images.githubusercontent.com/4397817/45837841-461f0600-bcde-11e8-860a-01da66d4001a.PNG)

My feeling is that this is possibly a paths issue.

**Comment by orbli** [comment]
I setup the server [here](http://139.162.70.235/bkdr/) with these commands
```
    1  apt install apache2
    2  apt update && apt upgrade -y
    3  apt install apache2 php7.2 php7.2-sqlite3 git
    4  phpenmod sqlite3
    5  phpenmod mcrypt
    6  apt-get -y install gcc make autoconf libc-dev pkg-config
    7  apt-get -y install libmcrypt-dev
    8  echo extension=mcrypt.so > /etc/php/7.2/apache2/conf.d/mcrypt.ini
    9  echo extension=mcrypt.so > /etc/php/7.2/cli/conf.d/mcrypt.ini
   10  a2enmod rewrite
   11  service apache2 restart
   12  cd /etc/apache2/
   13  ls
   14  vi apache2.conf
   15  cd /var/www
   16  git clone https://github.com/RecaMedia/Backdoor-Release.git
   17  mv Backdoor-Release/bkdr html/
   18  vi html/phpinfo.php
   19  chown -R www-data:www-data html/
   43  apt install php-pear
   44  apt install php7.2-dev
   45  pecl install mcrypt-1.0.1
   46  service apache2 restart

```

you can also view phpinfo [here](http://139.162.70.235/phpinfo.php)

**Comment by RecaMedia** [comment]
This is what I found on the call for the config file. You may need to downgrade the version of PHP since 7.2 is no longer has certain functions. If you can correct these issues, this may fix the problem.

![capture](https://user-images.githubusercontent.com/4397817/45844586-e1b97200-bcf0-11e8-9e02-086d9667ef04.PNG)

**Comment by orbli** [comment]
Actually I installed mcrypt for php7.2 manually so the functions should work.

Nevertheless if such deprecated warnings matter, then php7.1 also cannot work as they are deprecated in this version too (I just built and run it). Please suggest an environment for me.

**Comment by RecaMedia** [comment]
Try downgrading to PHP 5 with the installed modules to see if that works.

**Comment by Macemas** [comment]
My installation was on cPanel with php 5.6, sorry for the radio silence as I was on vacation. I tried your .htaccess as I didn't have anything in mine but it still wouldn't work. I seem to be having the same issue as Orbli. This issue is far over my head but I would like to help. I love the UI design. 

I'm getting the same connection refused at localhost:3001, as well as: 
![image](https://user-images.githubusercontent.com/41453496/46031254-3708d100-c0ad-11e8-9d50-0ba2592bab20.png)

The only errors I'm receiving in the network tab are relating to the connection refused at port 3001.

My installation is located at http://macemore.net/ICE (previously used directory, I tried a new one but it also didn't work) I've tried with HTTPS but that also didn't work. 

https://macemore.net/ICE/phpinfo.php

Maybe cPanel isn't the best platform to deploy this onto. I was hoping to be able to build my website live. Much like web builders but not.

**Comment by RecaMedia** [comment]
@Macemas @orbli try downloading my [latest release](https://github.com/RecaMedia/Backdoor-Release/releases/tag/v2.0.5). I made some minor updates so that the PHP doesn't rely on certain functions anymore. Try it out and let me know if this improves your experience on installation.

**Comment by Macemas** [comment]
> @Macemas @orbli try downloading my [latest release](https://github.com/RecaMedia/Backdoor-Release/releases/tag/v2.0.5). I made some minor updates so that the PHP doesn't rely on certain functions anymore. Try it out and let me know if this improves your experience on installation.

Here's what my developer console says this time, otherwise it's the same, infinitely loading: 
![image](https://user-images.githubusercontent.com/41453496/46158756-6ba69500-c233-11e8-9e12-7fe6fc80acde.png)

**Comment by RecaMedia** [comment]
> Here's what my developer console says this time, otherwise it's the same, infinitely loading:
> ![image](https://user-images.githubusercontent.com/41453496/46158756-6ba69500-c233-11e8-9e12-7fe6fc80acde.png)

In your case @Macemas, you are getting this error `Call to undefined function json_decode()`. Try this [https://serverfault.com/a/550461](https://serverfault.com/a/550461), or maybe upgrade to PHP 7.2. See here [https://stackoverflow.com/a/18239665](https://stackoverflow.com/a/18239665)

`json_encode` is a PHP function as seen [here](http://php.net/manual/en/function.json-encode.php), not sure why it isn't enabled, or you're running an older version of PHP that doesn't support it.

**Comment by Macemas** [comment]
> > Here's what my developer console says this time, otherwise it's the same, infinitely loading:
> > ![image](https://user-images.githubusercontent.com/41453496/46158756-6ba69500-c233-11e8-9e12-7fe6fc80acde.png)
> 
> In your case @Macemas, you are getting this error `Call to undefined function json_decode()`. Try this https://serverfault.com/a/550461, or maybe upgrade to PHP 7.2. See here https://stackoverflow.com/a/18239665
> 
> `json_encode` is a PHP function as seen [here](http://php.net/manual/en/function.json-encode.php), not sure why it isn't enabled, or you're running an older version of PHP that doesn't support it.

![image](https://user-images.githubusercontent.com/41453496/46220397-ce189780-c2fe-11e8-833f-b976feec4806.png)
Switched to PHP 7.2
![image](https://user-images.githubusercontent.com/41453496/46220418-dec90d80-c2fe-11e8-82a7-69c6b9c32a18.png)

It's like every turn there's a different issue :(

**Comment by RecaMedia** [comment]
Hey @Macemas, sorry for the issues you've been having but this seems more like an environment setup issue vs a problem with the app itself. So I'll close this ticket for now unless shown otherwise.

**Comment by Macemas** [comment]
I think it's an issue in regards to what the system requires. I've done everything to your specs, and yet it still doesn't work :(
I've changed permissions, htaccess, used several versions of PHP that include Mcrypt and SQLite3 that I've confirmed are enabled. I just setup bkdr again hoping it would work on a completely fresh system and it still doesn't :(

**Comment by RecaMedia** [comment]
Hey @Macemas, can you share any errors you're getting, whether on client side or server side? Obviously something is wrong, sorry for the issues. I would like to get this figured out to prevent others from having the same problems. This is a project I maintain along side many other projects I'm working on, response time may be delayed.

**Comment by Macemas** [comment]
The errors are the same as above, client side. As for server side I've not had any. I will attempt a clean installation and try again with elevated error logging and maybe that will help.

**Comment by Macemas** [comment]
Just tested the newest version on a fresh ubuntu install with LAMP stack. Still the same issues listed above, it also says that /api/config/ is not there (it's not)

**Comment by RecaMedia** [comment]
So I just tested locally a direct download from the repo, the only issue I ran into was the icon fonts not showing up properly. @Macemas can you send me a screenshot within inspector, under the network tab, all the responses you're getting when you receive the above errors? Make sure you have errors set to be displayed within your php.ini file.
