### ISSUE TITLE
Unable to install, not responding

### ISSUE THREAD

**Issue by luftaquila** [RecaMedia/Backdoor-Release#5]
My bkdr is running on https://luftaquila.iptime.org/bkdr and is not installing with some errors. 
I found similar issues at the bottom and read it, but I can't still fix it.

Errors are : 
bkdr.js:12 POST https://luftaquila.iptime.org/bkdr/api/config/ 404
bkdr.js:12 SyntaxError: Unexpected token < in JSON at position 0
bkdr.js:39 GET http://localhost:3001/socket.io/?EIO=3&transport=polling&t=M-ORUlN net::ERR_CONNECTION_REFUSED
.....

sqlite3 and mcrypt modules are installed, since they are visible on php -m command.
Also, my bkdr is running on nginx, not apache so there is no htaccess file I can set on it.

Thank you for your help in advance.

**Comment by RecaMedia** [comment]
Hi @luftaquila. Since you've mentioned that you're running on Nginx, I'm assuming the error is caused by the .htaccess files not working. You would have to read the .htaccess files, and create a replacement on Nginx. Here is a [article ](https://www.liquidweb.com/kb/convert-htaccess-rules-nginx-directives/)that I found that can possibly lead you on the right direction.

**Comment by luftaquila** [comment]
> Hi @luftaquila. Since you've mentioned that you're running on Nginx, I'm assuming the error is caused by the .htaccess files not working. You would have to read the .htaccess files, and create a replacement on Nginx. Here is a [article ](https://www.liquidweb.com/kb/convert-htaccess-rules-nginx-directives/)that I found that can possibly lead you on the right direction.

I think there is nothing I should do more. Your .htaccess example is :
<Directory /var/www/>
	Options Indexes FollowSymLinks
	AllowOverride None
	Require all granted
</Directory>

In NGINX, FollowSymLinks option equivalent is already set : http://nginx.org/en/docs/http/ngx_http_core_module.html#disable_symlinks
and for Indexes option, my server already have autoindex on; option.

Also, it seems like AllowOverride option is not needed in NGINX too. : 
https://stackoverflow.com/questions/35705641/how-to-convert-apaches-allowoverride-all-to-nginx

Lastly, I'm not sure but Require all granted option is not needed also. : 
https://stackoverflow.com/questions/42347760/nginx-working-with-apache-like-locations

I'm not sure what should I do to solve this. Please help.

**Comment by RecaMedia** [comment]
That was an example for the `/bkdr` directory. There is also one within [`/bkdr/api/.htaccess`](https://github.com/RecaMedia/Backdoor-Release/blob/master/bkdr/api/.htaccess) that needs to be replicated within Nginx.

Once you've completed that, if you're still having an error, please check the server logs to indicate what is wrong. This error `bkdr.js:12 SyntaxError: Unexpected token < in JSON at position 0` simply means the ajax call expected a JSON object as the return but did not receive it because of an error on the back-end.

**Comment by luftaquila** [comment]
@RecaMedia Hi! I've just received new version release message and tried again, but same error happens :(

Console says:
```
bkdr.js:1 SyntaxError: Unexpected token < in JSON at position 0
processErrors @ bkdr.js:1
(anonymous) @ bkdr.js:1
Promise.catch (async)
n.default @ bkdr.js:1
(anonymous) @ bkdr.js:1
g @ bkdr.js:1
(anonymous) @ bkdr.js:1
value @ bkdr.js:1
ls @ bkdr.js:1
(anonymous) @ bkdr.js:1
n.unstable_runWithPriority @ bkdr.js:1
Wi @ bkdr.js:1
xl @ bkdr.js:1
ul @ bkdr.js:1
ol @ bkdr.js:1
Wl @ bkdr.js:1
(anonymous) @ bkdr.js:1
fl @ bkdr.js:1
Jl @ bkdr.js:1
n.render @ bkdr.js:1
2../store @ bkdr.js:1
i @ bkdr.js:1
e @ bkdr.js:1
(anonymous) @ bkdr.js:1

GET http://localhost:3001/socket.io/?EIO=3&transport=polling&t=NKmlgBR net::ERR_CONNECTION_REFUSED
```

It seems like `Unexpected token < in JSON at position 0` appears because it requested non-existing file, so 404.html was returned and JSON.parse() throwing parse error.

In NGINX error.log, there are multiple errors saying:
```
2020/10/16 18:25:17 [error] 30293#30293: *10136 "/my/NGINX/webroot/directory/bkdr/api/config/index.php" is not found (2: No such file or directory), client: 192.168.0.1, server: luftaquila.io, request: "POST /bkdr/api/config/ HTTP/2.0", host: "luftaquila.io", referrer: "https://luftaquila.io/bkdr/"
```

Actually, there is no folder like /bkdr/api/config in source code and no process is listening on port 3001.
I have no idea.

**Comment by RecaMedia** [comment]
The /bkdr/api/config URL is the API endpoint. If it’s returning a 404, then you need to configure the /bkdr/api directory. There is a .htaccess file meant for Apache. You’ll need to convert that to work with NGINX .conf file.

Converter:
https://winginx.com/en/htaccess


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
